server:
  port: 8080
spring:
  application:
    name: go-healthy-api
  datasource:
    url: jdbc:postgresql://localhost:5432/gohealthy_api
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'