version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gohealthy_api
    ports:
      - 5432:5432
  wiremock:
    image: "wiremock/wiremock:3.0.0-1-alpine"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    ports:
      - 9999:8080
